name: Create tag

on:
    # pull_request_target:
    #     types:
    #     - closed
    #     branches:
    #     - 'release/v*'
    push:
        branches:
        - 'release/v*'

jobs:
    if_merged:
        # if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
        - id: get_version
          uses: baileyherbert/version-action@v3
    
        - name: Create tag
          uses: actions/github-script@v7
          with:
            script: |
                github.rest.git.createRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: 'refs/tags/${{ steps.get_version.outputs.version }}',
                    sha: context.sha
                })
        