name: Create tag

on:
    # pull_request_target:
    #     types:
    #     - closed
    #     branches:
    #     - 'release/v*'
    push:
        branches:
        - 'release/v*'

jobs:
    if_merged:
        # if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
        - name: Create tag
          uses: actions/github-script@v7
          with:
            script: |
                tagname=$(echo ${{ github.ref }} | sed -n 's/refs\/heads\/release\/v\(.*\)/\1/p')
                echo "Creating tag $tagname"
        # github.rest.git.createRef({
        #     owner: context.repo.owner,
        #     repo: context.repo.repo,
        #     ref: 'refs/tags/v$tagname',
        #     sha: context.sha
        # })
        